services:
  - type: web
    name: superstore-dashboard
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn trabajo:app.server"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
